# Generated by Django 5.2.17 on 2026-09-24 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("support", "고객센터 문의"),
                            ("ad", "광고/제휴 문의"),
                        ],
                        default="support",
                        max_length=20,
                        verbose_name="문의 유형",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름(회사명)")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="회신 받을 이메일"),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="제목")),
                ("message", models.TextField(max_length=3000, verbose_name="내용")),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="메일 발송 성공"),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="답변 완료"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="접수일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="로그인 회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "문의",
                "verbose_name_plural": "문의 관리",
                "ordering": ["-created_at"],
            },
        ),
    ]
