# Generated by Django 5.2.17 on 2026-09-25 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_inquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageViewDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="날짜")),
                ("path", models.CharField(max_length=200, verbose_name="페이지 주소")),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
            ],
            options={
                "verbose_name": "일별 페이지 조회",
                "verbose_name_plural": "일별 페이지 조회",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "path"), name="unique_path_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitorDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="날짜")),
                (
                    "visitor_hash",
                    models.CharField(max_length=64, verbose_name="방문자 식별값(해시)"),
                ),
                (
                    "page_views",
                    models.PositiveIntegerField(default=0, verbose_name="페이지뷰"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="유입 경로"
                    ),
                ),
                (
                    "is_mobile",
                    models.BooleanField(default=False, verbose_name="모바일"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="첫 방문 시각"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, verbose_name="마지막 활동 시각"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_days",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "일별 방문자",
                "verbose_name_plural": "일별 방문자",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "visitor_hash"), name="unique_visitor_per_day"
                    )
                ],
            },
        ),
    ]
