# Generated by Django 5.2.17 on 2026-09-23 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Duel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="주제")),
                ("description", models.TextField(blank=True, verbose_name="부연 설명")),
                ("start_at", models.DateTimeField(verbose_name="시작 시각")),
                ("end_at", models.DateTimeField(verbose_name="투표 마감 시각")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "대기중"),
                            ("active", "진행중"),
                            ("finished", "종료"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_as_challenger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="도전자",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_as_opponent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="상대",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duels_won",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승자",
                    ),
                ),
            ],
            options={
                "verbose_name": "1:1 일기토",
                "verbose_name_plural": "1:1 일기토 관리",
                "ordering": ["-start_at"],
            },
        ),
        migrations.CreateModel(
            name="DuelVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("challenger", "도전자"), ("opponent", "상대")],
                        max_length=20,
                        verbose_name="선택",
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="투표일"),
                ),
                (
                    "duel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="duels.duel",
                        verbose_name="일기토",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duel_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="투표한 회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "일기토 투표",
                "verbose_name_plural": "일기토 투표 관리",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("duel", "voter"), name="unique_duel_vote_per_user"
                    )
                ],
            },
        ),
    ]
