# Generated by Django 5.2.17 on 2026-09-22 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='party',
            field=models.CharField(blank=True, choices=[('conservative', '보수'), ('democrat', '진보')], max_length=20, verbose_name='진영'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 아이디입니다.'}, help_text='영문/숫자 4~20자 (특수문자/한글 불가)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='아이디는 4자 이상이어야 합니다.'), django.core.validators.RegexValidator(message='아이디는 영문과 숫자만 사용할 수 있습니다. (특수문자, 한글, 공백 불가)', regex='^[A-Za-z0-9]+$')], verbose_name='아이디'),
        ),
    ]
