# Generated by Django 5.2.17 on 2026-09-23 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_points_and_duel_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "남성"), ("female", "여성")],
                max_length=10,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                error_messages={"unique": "이미 사용 중인 닉네임입니다."},
                help_text="한글/영문/숫자 2~15자",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="닉네임은 2자 이상이어야 합니다."
                    )
                ],
                verbose_name="닉네임",
            ),
        ),
    ]
