# Generated by Django 5.2.17 on 2026-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_gender_alter_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="탈퇴일"),
        ),
    ]
