# Generated by Django 5.2.17 on 2026-09-22 07:28

import boards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=boards.models.post_image_upload_to, verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boards.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부 이미지',
                'verbose_name_plural': '첨부 이미지 관리',
                'ordering': ['id'],
            },
        ),
    ]
