# Generated by Django 5.2.17 on 2026-09-25 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_comment_postlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "추천"), (-1, "반대")], verbose_name="추천/반대"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="일시"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="boards.comment",
                        verbose_name="댓글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글 추천/반대",
                "verbose_name_plural": "댓글 추천/반대 관리",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comment", "user"), name="unique_comment_vote_per_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PostDislike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="반대일"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dislikes",
                        to="boards.post",
                        verbose_name="게시글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_dislikes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="반대한 회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "반대",
                "verbose_name_plural": "반대 관리",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "user"), name="unique_post_dislike_per_user"
                    )
                ],
            },
        ),
    ]
